name: Publish Cloud
# Required secrets for this workflow: MAINTAIN_USERNAME, MAINTAIN_EMAIL, SLACK_TOKEN, SLACK_CHANNELS, MAINTAIN_TOKEN, REMOTE_PUBLISH_REPO

on:
  repository_dispatch:
    types: [deploy-cloud]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release branch version'
        required: false
      pre_release:
        type: boolean
        description: 'Is this a pre-release?'
        required: false
      repository_name:
        type: string
        description: 'Repository to publish to'
        required: true

  workflow_call:
    inputs:
      version:
        type: string
        description: 'Release branch version'
        required: false
      pre_release:
        type: boolean
        description: 'Is this a pre-release?'
        required: false

jobs:
  bump-version:
    runs-on: ubuntu-20.04
    outputs:
      prev_version: ${{ steps.bump_version_step.outputs.prev_version }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          repository: ${{ github.event.client_payload.repository || inputs.repository_name }}
          path: ./tmp/checkout
      - name: Copy Files To Workspace
        shell: bash
        run: |
          sudo apt-get install rsync -y
          rm ./tmp/checkout/.github/workflows/publish-cloud.yml
          rm -rf ./tmp/checkout/.git
          rsync -avu ./tmp/checkout/ .
      - name: Get Configuration
        id: configuration
        uses: antifree/json-to-variables@v1.0.1
        with: 
            filename: './.github/workflows/config.json'
            prefix: config
      - name: Test permissions
        uses: ./.github/workflows/permissions
        with:
          ENVIRONMENT: ${{ env.config_deployment_environment }}
          DEPLOYMENT_PERMITTED: ${{ env.config_deployment_permitted }}
          DEPLOYMENT_REPOSITORY: ${{ github.config_deployment_repository || inputs.repository_name }}
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get next release branch
        uses: ./get-next-release-branch
        with:
          INPUT_VERSION: ${{ github.event.client_payload.version || inputs.version }}
      # - name: Get Current SHA
      #   shell: bash
      #   run: |
      #     echo $(git rev-parse HEAD)
      #     echo "CURRENT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      # - name: Validate Run Checks
      #   uses : ./validate-run-checks
      #   with:
      #     TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      #     REPOSITORY: ${{ github.event.client_payload.repository  || inputs.repository_name }}
      #     CURRENT_SHA: ${{ env.CURRENT_SHA }}
      #     IGNORE_CHECKS_LIST: "publish-to-cloud" # Comma separated list of checks to ignore
      - name: Bump version
        id: bump_version_step
        uses: ./bump-version
        with:
          CHANNEL: "cloud"
      - name: Push version
        uses : ./push-new-version
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          COMMIT_MESSAGE: "Bump ${{ env.PACKAGE_VERSION || github.event.client_payload.version || inputs.version }}"
  publish-to-cloud:
    needs: bump-version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          repository: ${{ github.event.client_payload.repository || inputs.repository_name }}
      - name: Install Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get next release branch
        uses: ./get-next-release-branch
        with:
          INPUT_VERSION: ${{ github.event.inputs.version }}
      - name: Checkout next release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MAINTAIN_TOKEN }}
          ref: ${{ env.RELEASE_BRANCH }}
          repository: ${{ github.event.client_payload.repository || inputs.repository_name }}
      - name: Install Dependencies
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').last_cloud_version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          npm ci
      - name: Build plugin
        uses: ./build-plugin
        with:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          SCRIPT_PATH: "./.github/scripts/build-zip.sh"
      - name: Upload zip file to GitHub actions artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_ZIP_FILENAME }}
          path: ${{ env.PLUGIN_ZIP_PATH }}
          if-no-files-found: error
      - name: Create Git tag
        uses : ./create-git-tag
        with:
          MAINTAIN_USERNAME: ${{ secrets.MAINTAIN_USERNAME }}
          MAINTAIN_EMAIL: ${{ secrets.MAINTAIN_EMAIL }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      - name: Generate changelog
        uses : ./generate-changelog
        with:
          TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
          REPOSITORY: ${{ github.event.client_payload.repository || inputs.repository_name }}
          HEAD_BRANCH_NAME: v${{ env.PACKAGE_VERSION }}
          BASE_TAG_NAME: v${{ needs.bump-version.outputs.prev_version }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: elementor-*.zip
          prerelease: ${{ github.event.client_payload.pre_release  || inputs.pre_release }}
          body_path: temp-changelog.txt
          repository: ${{ github.event.client_payload.repository || inputs.repository_name }}
          token: ${{ secrets.MAINTAIN_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.MAINTAIN_TOKEN }}
      - name: Send slack message
        uses: ./slack-notify
        with:
          MESSAGE: "@here Elementor ${{ env.PACKAGE_VERSION }} has been released! Saddle up partners! :tada:"
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNELS }}
